[package]
name = "aurora-filters"
description = "Filter and adjustment node implementations."
version.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
aurora-core = { workspace = true }
aurora-gpu = { workspace = true }
aurora-graph = { workspace = true }
aurora-color = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
