[package]
name = "aurora-text"
description = "Shaping, layout, OpenType handling, and text on path."
version.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
aurora-core = { workspace = true }
aurora-vector = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
